[2025-04-02T09:06:23Z INFO  ul_jvm] uLambda's JVM version 0.1.0
[src/class/parser.rs:24 | offset 0x4] minor_version = 0x0
[src/class/parser.rs:24 | offset 0x6] major_version = 0x3d
[src/class/parser.rs:24 | offset 0x8] constant_pool_count = 0x32
[src/class/parser.rs:24 | offset 0xa] constant_pool = [
    Ignored,
    Methodref {
        class_index: 0x2,
        name_and_type_index: 0x3,
    },
    Class {
        name_index: 0x4,
    },
    NameAndType {
        name: 0x5,
        descriptor_index: 0x6,
    },
    Utf8 {
        length: 0x10,
        bytes: ModifiedUtf8String(
            [
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x4f,
                0x62,
                0x6a,
                0x65,
                0x63,
                0x74,
            ],
        ),
    },
    Utf8 {
        length: 0x6,
        bytes: ModifiedUtf8String(
            [
                0x3c,
                0x69,
                0x6e,
                0x69,
                0x74,
                0x3e,
            ],
        ),
    },
    Utf8 {
        length: 0x3,
        bytes: ModifiedUtf8String(
            [
                0x28,
                0x29,
                0x56,
            ],
        ),
    },
    Long {
        high_bytes: 0x0,
        low_bytes: 0x5,
    },
    Ignored,
    Double {
        high_bytes: 0x40250000,
        low_bytes: 0x0,
    },
    Ignored,
    Fieldref {
        class_index: 0xc,
        name_and_type_index: 0xd,
    },
    Class {
        name_index: 0xe,
    },
    NameAndType {
        name: 0xf,
        descriptor_index: 0x10,
    },
    Utf8 {
        length: 0x10,
        bytes: ModifiedUtf8String(
            [
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x53,
                0x79,
                0x73,
                0x74,
                0x65,
                0x6d,
            ],
        ),
    },
    Utf8 {
        length: 0x3,
        bytes: ModifiedUtf8String(
            [
                0x6f,
                0x75,
                0x74,
            ],
        ),
    },
    Utf8 {
        length: 0x15,
        bytes: ModifiedUtf8String(
            [
                0x4c,
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x69,
                0x6f,
                0x2f,
                0x50,
                0x72,
                0x69,
                0x6e,
                0x74,
                0x53,
                0x74,
                0x72,
                0x65,
                0x61,
                0x6d,
                0x3b,
            ],
        ),
    },
    DynamicInvoke {
        bootstrap_method_attr_index: 0x0,
        name_and_type_index: 0x12,
    },
    NameAndType {
        name: 0x13,
        descriptor_index: 0x14,
    },
    Utf8 {
        length: 0x17,
        bytes: ModifiedUtf8String(
            [
                0x6d,
                0x61,
                0x6b,
                0x65,
                0x43,
                0x6f,
                0x6e,
                0x63,
                0x61,
                0x74,
                0x57,
                0x69,
                0x74,
                0x68,
                0x43,
                0x6f,
                0x6e,
                0x73,
                0x74,
                0x61,
                0x6e,
                0x74,
                0x73,
            ],
        ),
    },
    Utf8 {
        length: 0x16,
        bytes: ModifiedUtf8String(
            [
                0x28,
                0x4a,
                0x44,
                0x29,
                0x4c,
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x53,
                0x74,
                0x72,
                0x69,
                0x6e,
                0x67,
                0x3b,
            ],
        ),
    },
    Methodref {
        class_index: 0x16,
        name_and_type_index: 0x17,
    },
    Class {
        name_index: 0x18,
    },
    NameAndType {
        name: 0x19,
        descriptor_index: 0x1a,
    },
    Utf8 {
        length: 0x13,
        bytes: ModifiedUtf8String(
            [
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x69,
                0x6f,
                0x2f,
                0x50,
                0x72,
                0x69,
                0x6e,
                0x74,
                0x53,
                0x74,
                0x72,
                0x65,
                0x61,
                0x6d,
            ],
        ),
    },
    Utf8 {
        length: 0x7,
        bytes: ModifiedUtf8String(
            [
                0x70,
                0x72,
                0x69,
                0x6e,
                0x74,
                0x6c,
                0x6e,
            ],
        ),
    },
    Utf8 {
        length: 0x15,
        bytes: ModifiedUtf8String(
            [
                0x28,
                0x4c,
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x53,
                0x74,
                0x72,
                0x69,
                0x6e,
                0x67,
                0x3b,
                0x29,
                0x56,
            ],
        ),
    },
    Class {
        name_index: 0x1c,
    },
    Utf8 {
        length: 0x4,
        bytes: ModifiedUtf8String(
            [
                0x4d,
                0x61,
                0x69,
                0x6e,
            ],
        ),
    },
    Utf8 {
        length: 0x4,
        bytes: ModifiedUtf8String(
            [
                0x43,
                0x6f,
                0x64,
                0x65,
            ],
        ),
    },
    Utf8 {
        length: 0xf,
        bytes: ModifiedUtf8String(
            [
                0x4c,
                0x69,
                0x6e,
                0x65,
                0x4e,
                0x75,
                0x6d,
                0x62,
                0x65,
                0x72,
                0x54,
                0x61,
                0x62,
                0x6c,
                0x65,
            ],
        ),
    },
    Utf8 {
        length: 0x4,
        bytes: ModifiedUtf8String(
            [
                0x6d,
                0x61,
                0x69,
                0x6e,
            ],
        ),
    },
    Utf8 {
        length: 0x16,
        bytes: ModifiedUtf8String(
            [
                0x28,
                0x5b,
                0x4c,
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x53,
                0x74,
                0x72,
                0x69,
                0x6e,
                0x67,
                0x3b,
                0x29,
                0x56,
            ],
        ),
    },
    Utf8 {
        length: 0xa,
        bytes: ModifiedUtf8String(
            [
                0x53,
                0x6f,
                0x75,
                0x72,
                0x63,
                0x65,
                0x46,
                0x69,
                0x6c,
                0x65,
            ],
        ),
    },
    Utf8 {
        length: 0x9,
        bytes: ModifiedUtf8String(
            [
                0x4d,
                0x61,
                0x69,
                0x6e,
                0x2e,
                0x6a,
                0x61,
                0x76,
                0x61,
            ],
        ),
    },
    Utf8 {
        length: 0x10,
        bytes: ModifiedUtf8String(
            [
                0x42,
                0x6f,
                0x6f,
                0x74,
                0x73,
                0x74,
                0x72,
                0x61,
                0x70,
                0x4d,
                0x65,
                0x74,
                0x68,
                0x6f,
                0x64,
                0x73,
            ],
        ),
    },
    MethodHandle {
        reference_kind: 0x6,
        reference_index: 0x25,
    },
    Methodref {
        class_index: 0x26,
        name_and_type_index: 0x27,
    },
    Class {
        name_index: 0x28,
    },
    NameAndType {
        name: 0x13,
        descriptor_index: 0x29,
    },
    Utf8 {
        length: 0x24,
        bytes: ModifiedUtf8String(
            [
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x69,
                0x6e,
                0x76,
                0x6f,
                0x6b,
                0x65,
                0x2f,
                0x53,
                0x74,
                0x72,
                0x69,
                0x6e,
                0x67,
                0x43,
                0x6f,
                0x6e,
                0x63,
                0x61,
                0x74,
                0x46,
                0x61,
                0x63,
                0x74,
                0x6f,
                0x72,
                0x79,
            ],
        ),
    },
    Utf8 {
        length: 0x98,
        bytes: ModifiedUtf8String(
            [
                0x28,
                0x4c,
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x69,
                0x6e,
                0x76,
                0x6f,
                0x6b,
                0x65,
                0x2f,
                0x4d,
                0x65,
                0x74,
                0x68,
                0x6f,
                0x64,
                0x48,
                0x61,
                0x6e,
                0x64,
                0x6c,
                0x65,
                0x73,
                0x24,
                0x4c,
                0x6f,
                0x6f,
                0x6b,
                0x75,
                0x70,
                0x3b,
                0x4c,
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x53,
                0x74,
                0x72,
                0x69,
                0x6e,
                0x67,
                0x3b,
                0x4c,
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x69,
                0x6e,
                0x76,
                0x6f,
                0x6b,
                0x65,
                0x2f,
                0x4d,
                0x65,
                0x74,
                0x68,
                0x6f,
                0x64,
                0x54,
                0x79,
                0x70,
                0x65,
                0x3b,
                0x4c,
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x53,
                0x74,
                0x72,
                0x69,
                0x6e,
                0x67,
                0x3b,
                0x5b,
                0x4c,
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x4f,
                0x62,
                0x6a,
                0x65,
                0x63,
                0x74,
                0x3b,
                0x29,
                0x4c,
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x69,
                0x6e,
                0x76,
                0x6f,
                0x6b,
                0x65,
                0x2f,
                0x43,
                0x61,
                0x6c,
                0x6c,
                0x53,
                0x69,
                0x74,
                0x65,
                0x3b,
            ],
        ),
    },
    String {
        string_index: 0x2b,
    },
    Utf8 {
        length: 0xf,
        bytes: ModifiedUtf8String(
            [
                0x5a,
                0x41,
                0x52,
                0x4d,
                0x41,
                0x3a,
                0x20,
                0x1,
                0x20,
                0x57,
                0x4f,
                0x57,
                0x3a,
                0x20,
                0x1,
            ],
        ),
    },
    Utf8 {
        length: 0xc,
        bytes: ModifiedUtf8String(
            [
                0x49,
                0x6e,
                0x6e,
                0x65,
                0x72,
                0x43,
                0x6c,
                0x61,
                0x73,
                0x73,
                0x65,
                0x73,
            ],
        ),
    },
    Class {
        name_index: 0x2e,
    },
    Utf8 {
        length: 0x25,
        bytes: ModifiedUtf8String(
            [
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x69,
                0x6e,
                0x76,
                0x6f,
                0x6b,
                0x65,
                0x2f,
                0x4d,
                0x65,
                0x74,
                0x68,
                0x6f,
                0x64,
                0x48,
                0x61,
                0x6e,
                0x64,
                0x6c,
                0x65,
                0x73,
                0x24,
                0x4c,
                0x6f,
                0x6f,
                0x6b,
                0x75,
                0x70,
            ],
        ),
    },
    Class {
        name_index: 0x30,
    },
    Utf8 {
        length: 0x1e,
        bytes: ModifiedUtf8String(
            [
                0x6a,
                0x61,
                0x76,
                0x61,
                0x2f,
                0x6c,
                0x61,
                0x6e,
                0x67,
                0x2f,
                0x69,
                0x6e,
                0x76,
                0x6f,
                0x6b,
                0x65,
                0x2f,
                0x4d,
                0x65,
                0x74,
                0x68,
                0x6f,
                0x64,
                0x48,
                0x61,
                0x6e,
                0x64,
                0x6c,
                0x65,
                0x73,
            ],
        ),
    },
    Utf8 {
        length: 0x6,
        bytes: ModifiedUtf8String(
            [
                0x4c,
                0x6f,
                0x6f,
                0x6b,
                0x75,
                0x70,
            ],
        ),
    },
]
[src/class/parser.rs:24 | offset 0x2c9] access_flags = [
    AccPublic,
    AccSuper,
]
[2025-04-02T09:06:23Z DEBUG ul_jvm] parsed: ClassFile {
        minor_version: 0,
        major_version: 61,
        constant_pool_count: 50,
        constant_pool: [
            Ignored,
            Methodref {
                class_index: 2,
                name_and_type_index: 3,
            },
            Class {
                name_index: 4,
            },
            NameAndType {
                name: 5,
                descriptor_index: 6,
            },
            Utf8 {
                length: 16,
                bytes: ModifiedUtf8String(
                    [
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        79,
                        98,
                        106,
                        101,
                        99,
                        116,
                    ],
                ),
            },
            Utf8 {
                length: 6,
                bytes: ModifiedUtf8String(
                    [
                        60,
                        105,
                        110,
                        105,
                        116,
                        62,
                    ],
                ),
            },
            Utf8 {
                length: 3,
                bytes: ModifiedUtf8String(
                    [
                        40,
                        41,
                        86,
                    ],
                ),
            },
            Long {
                high_bytes: 0,
                low_bytes: 5,
            },
            Ignored,
            Double {
                high_bytes: 1076166656,
                low_bytes: 0,
            },
            Ignored,
            Fieldref {
                class_index: 12,
                name_and_type_index: 13,
            },
            Class {
                name_index: 14,
            },
            NameAndType {
                name: 15,
                descriptor_index: 16,
            },
            Utf8 {
                length: 16,
                bytes: ModifiedUtf8String(
                    [
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        83,
                        121,
                        115,
                        116,
                        101,
                        109,
                    ],
                ),
            },
            Utf8 {
                length: 3,
                bytes: ModifiedUtf8String(
                    [
                        111,
                        117,
                        116,
                    ],
                ),
            },
            Utf8 {
                length: 21,
                bytes: ModifiedUtf8String(
                    [
                        76,
                        106,
                        97,
                        118,
                        97,
                        47,
                        105,
                        111,
                        47,
                        80,
                        114,
                        105,
                        110,
                        116,
                        83,
                        116,
                        114,
                        101,
                        97,
                        109,
                        59,
                    ],
                ),
            },
            DynamicInvoke {
                bootstrap_method_attr_index: 0,
                name_and_type_index: 18,
            },
            NameAndType {
                name: 19,
                descriptor_index: 20,
            },
            Utf8 {
                length: 23,
                bytes: ModifiedUtf8String(
                    [
                        109,
                        97,
                        107,
                        101,
                        67,
                        111,
                        110,
                        99,
                        97,
                        116,
                        87,
                        105,
                        116,
                        104,
                        67,
                        111,
                        110,
                        115,
                        116,
                        97,
                        110,
                        116,
                        115,
                    ],
                ),
            },
            Utf8 {
                length: 22,
                bytes: ModifiedUtf8String(
                    [
                        40,
                        74,
                        68,
                        41,
                        76,
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        83,
                        116,
                        114,
                        105,
                        110,
                        103,
                        59,
                    ],
                ),
            },
            Methodref {
                class_index: 22,
                name_and_type_index: 23,
            },
            Class {
                name_index: 24,
            },
            NameAndType {
                name: 25,
                descriptor_index: 26,
            },
            Utf8 {
                length: 19,
                bytes: ModifiedUtf8String(
                    [
                        106,
                        97,
                        118,
                        97,
                        47,
                        105,
                        111,
                        47,
                        80,
                        114,
                        105,
                        110,
                        116,
                        83,
                        116,
                        114,
                        101,
                        97,
                        109,
                    ],
                ),
            },
            Utf8 {
                length: 7,
                bytes: ModifiedUtf8String(
                    [
                        112,
                        114,
                        105,
                        110,
                        116,
                        108,
                        110,
                    ],
                ),
            },
            Utf8 {
                length: 21,
                bytes: ModifiedUtf8String(
                    [
                        40,
                        76,
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        83,
                        116,
                        114,
                        105,
                        110,
                        103,
                        59,
                        41,
                        86,
                    ],
                ),
            },
            Class {
                name_index: 28,
            },
            Utf8 {
                length: 4,
                bytes: ModifiedUtf8String(
                    [
                        77,
                        97,
                        105,
                        110,
                    ],
                ),
            },
            Utf8 {
                length: 4,
                bytes: ModifiedUtf8String(
                    [
                        67,
                        111,
                        100,
                        101,
                    ],
                ),
            },
            Utf8 {
                length: 15,
                bytes: ModifiedUtf8String(
                    [
                        76,
                        105,
                        110,
                        101,
                        78,
                        117,
                        109,
                        98,
                        101,
                        114,
                        84,
                        97,
                        98,
                        108,
                        101,
                    ],
                ),
            },
            Utf8 {
                length: 4,
                bytes: ModifiedUtf8String(
                    [
                        109,
                        97,
                        105,
                        110,
                    ],
                ),
            },
            Utf8 {
                length: 22,
                bytes: ModifiedUtf8String(
                    [
                        40,
                        91,
                        76,
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        83,
                        116,
                        114,
                        105,
                        110,
                        103,
                        59,
                        41,
                        86,
                    ],
                ),
            },
            Utf8 {
                length: 10,
                bytes: ModifiedUtf8String(
                    [
                        83,
                        111,
                        117,
                        114,
                        99,
                        101,
                        70,
                        105,
                        108,
                        101,
                    ],
                ),
            },
            Utf8 {
                length: 9,
                bytes: ModifiedUtf8String(
                    [
                        77,
                        97,
                        105,
                        110,
                        46,
                        106,
                        97,
                        118,
                        97,
                    ],
                ),
            },
            Utf8 {
                length: 16,
                bytes: ModifiedUtf8String(
                    [
                        66,
                        111,
                        111,
                        116,
                        115,
                        116,
                        114,
                        97,
                        112,
                        77,
                        101,
                        116,
                        104,
                        111,
                        100,
                        115,
                    ],
                ),
            },
            MethodHandle {
                reference_kind: 6,
                reference_index: 37,
            },
            Methodref {
                class_index: 38,
                name_and_type_index: 39,
            },
            Class {
                name_index: 40,
            },
            NameAndType {
                name: 19,
                descriptor_index: 41,
            },
            Utf8 {
                length: 36,
                bytes: ModifiedUtf8String(
                    [
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        105,
                        110,
                        118,
                        111,
                        107,
                        101,
                        47,
                        83,
                        116,
                        114,
                        105,
                        110,
                        103,
                        67,
                        111,
                        110,
                        99,
                        97,
                        116,
                        70,
                        97,
                        99,
                        116,
                        111,
                        114,
                        121,
                    ],
                ),
            },
            Utf8 {
                length: 152,
                bytes: ModifiedUtf8String(
                    [
                        40,
                        76,
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        105,
                        110,
                        118,
                        111,
                        107,
                        101,
                        47,
                        77,
                        101,
                        116,
                        104,
                        111,
                        100,
                        72,
                        97,
                        110,
                        100,
                        108,
                        101,
                        115,
                        36,
                        76,
                        111,
                        111,
                        107,
                        117,
                        112,
                        59,
                        76,
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        83,
                        116,
                        114,
                        105,
                        110,
                        103,
                        59,
                        76,
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        105,
                        110,
                        118,
                        111,
                        107,
                        101,
                        47,
                        77,
                        101,
                        116,
                        104,
                        111,
                        100,
                        84,
                        121,
                        112,
                        101,
                        59,
                        76,
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        83,
                        116,
                        114,
                        105,
                        110,
                        103,
                        59,
                        91,
                        76,
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        79,
                        98,
                        106,
                        101,
                        99,
                        116,
                        59,
                        41,
                        76,
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        105,
                        110,
                        118,
                        111,
                        107,
                        101,
                        47,
                        67,
                        97,
                        108,
                        108,
                        83,
                        105,
                        116,
                        101,
                        59,
                    ],
                ),
            },
            String {
                string_index: 43,
            },
            Utf8 {
                length: 15,
                bytes: ModifiedUtf8String(
                    [
                        90,
                        65,
                        82,
                        77,
                        65,
                        58,
                        32,
                        1,
                        32,
                        87,
                        79,
                        87,
                        58,
                        32,
                        1,
                    ],
                ),
            },
            Utf8 {
                length: 12,
                bytes: ModifiedUtf8String(
                    [
                        73,
                        110,
                        110,
                        101,
                        114,
                        67,
                        108,
                        97,
                        115,
                        115,
                        101,
                        115,
                    ],
                ),
            },
            Class {
                name_index: 46,
            },
            Utf8 {
                length: 37,
                bytes: ModifiedUtf8String(
                    [
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        105,
                        110,
                        118,
                        111,
                        107,
                        101,
                        47,
                        77,
                        101,
                        116,
                        104,
                        111,
                        100,
                        72,
                        97,
                        110,
                        100,
                        108,
                        101,
                        115,
                        36,
                        76,
                        111,
                        111,
                        107,
                        117,
                        112,
                    ],
                ),
            },
            Class {
                name_index: 48,
            },
            Utf8 {
                length: 30,
                bytes: ModifiedUtf8String(
                    [
                        106,
                        97,
                        118,
                        97,
                        47,
                        108,
                        97,
                        110,
                        103,
                        47,
                        105,
                        110,
                        118,
                        111,
                        107,
                        101,
                        47,
                        77,
                        101,
                        116,
                        104,
                        111,
                        100,
                        72,
                        97,
                        110,
                        100,
                        108,
                        101,
                        115,
                    ],
                ),
            },
            Utf8 {
                length: 6,
                bytes: ModifiedUtf8String(
                    [
                        76,
                        111,
                        111,
                        107,
                        117,
                        112,
                    ],
                ),
            },
        ],
        access_flags: [
            AccPublic,
            AccSuper,
        ],
        this_class: 27,
        super_class: 2,
        interfaces_count: 0,
        interfaces: [],
        fields_count: 0,
        fields: [],
        methods_count: 2,
        methods: [
            MethodInfo {
                access_flags: [
                    AccPublic,
                ],
                name_index: 5,
                descriptor_index: 6,
                attributes_count: 1,
                attributes: [
                    AttributeInfo {
                        attribute_name_index: 29,
                        attribute_length: 29,
                        info: [
                            0,
                            1,
                            0,
                            1,
                            0,
                            0,
                            0,
                            5,
                            42,
                            183,
                            0,
                            1,
                            177,
                            0,
                            0,
                            0,
                            1,
                            0,
                            30,
                            0,
                            0,
                            0,
                            6,
                            0,
                            1,
                            0,
                            0,
                            0,
                            1,
                        ],
                    },
                ],
            },
            MethodInfo {
                access_flags: [
                    AccPublic,
                    AccStatic,
                ],
                name_index: 31,
                descriptor_index: 32,
                attributes_count: 1,
                attributes: [
                    AttributeInfo {
                        attribute_name_index: 29,
                        attribute_length: 58,
                        info: [
                            0,
                            5,
                            0,
                            5,
                            0,
                            0,
                            0,
                            22,
                            20,
                            0,
                            7,
                            64,
                            20,
                            0,
                            9,
                            74,
                            178,
                            0,
                            11,
                            31,
                            41,
                            186,
                            0,
                            17,
                            0,
                            0,
                            182,
                            0,
                            21,
                            177,
                            0,
                            0,
                            0,
                            1,
                            0,
                            30,
                            0,
                            0,
                            0,
                            18,
                            0,
                            4,
                            0,
                            0,
                            0,
                            3,
                            0,
                            4,
                            0,
                            4,
                            0,
                            8,
                            0,
                            6,
                            0,
                            21,
                            0,
                            7,
                        ],
                    },
                ],
            },
        ],
        attributes_count: 3,
        attributes: [
            AttributeInfo {
                attribute_name_index: 33,
                attribute_length: 2,
                info: [
                    0,
                    34,
                ],
            },
            AttributeInfo {
                attribute_name_index: 35,
                attribute_length: 8,
                info: [
                    0,
                    1,
                    0,
                    36,
                    0,
                    1,
                    0,
                    42,
                ],
            },
            AttributeInfo {
                attribute_name_index: 44,
                attribute_length: 10,
                info: [
                    0,
                    1,
                    0,
                    45,
                    0,
                    47,
                    0,
                    49,
                    0,
                    25,
                ],
            },
        ],
    }
